#!/bin/bash

for net in fc1 fc2 fc3 fc4 fc5
do
	for k in 0 1;
	do
		for spec in `ls ../test_cases/net${k}_${net}`
		do
			echo -n net${k}_${net},${spec},
			python verifier.py --net net${k}_${net} --spec ../test_cases/net${k}_${net}/${spec} --num_iter 100 --verbosity 0
		done
	done
done
